[package]
name = "grpc_examples_greeter"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false

[lib]
doctest = false
test = false

[dependencies.grpc]
path = "../../grpc"
[dependencies.grpc-protobuf]
path = "../../grpc-protobuf"

[dependencies]
protobuf        = "3"
futures         = "0.1.*"
futures-cpupool = "0.1.*"
tls-api            = "0.2.*"
tls-api-native-tls = "0.2.*"
#httpbis         = "~0.7"
httpbis         = { git = "https://github.com/stepancheg/rust-http2" }
env_logger      = "~0.5"

[build-dependencies]
protoc-rust-grpc = { path = "../../protoc-rust-grpc" }

[[bin]]
name = "greeter_client"
test = false

[[bin]]
name = "greeter_client_multi"
test = false

[[bin]]
name = "greeter_server"
test = false

[[bin]]
name = "greeter_server_multi_server"
test = false
